id: P1FD19E88
initial_creation_type: input
source_metadata:
  title: Vaitānaśrautasūtra (= Vaitānasūtra)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Śrautasūtra
  data entry: Arlo Griffiths
  contribution to GRETIL: Arlo Griffiths
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:49:00.306449'
last_modified_at: '2022-03-09T14:49:00.306462'
